# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/malibu/Git/DreamPark/UI/consumer.ui'
#
# Created: Wed Jan 14 11:35:51 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_consumer_home(object):
    def setupUi(self, consumer_home):
        consumer_home.setObjectName(_fromUtf8("consumer_home"))
        consumer_home.resize(549, 336)
        self.centralwidget = QtGui.QWidget(consumer_home)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.subscribed = QtGui.QFrame(self.centralwidget)
        self.subscribed.setEnabled(True)
        self.subscribed.setGeometry(QtCore.QRect(0, 0, 551, 341))
        self.subscribed.setAccessibleDescription(_fromUtf8(""))
        self.subscribed.setAutoFillBackground(True)
        self.subscribed.setFrameShape(QtGui.QFrame.Panel)
        self.subscribed.setFrameShadow(QtGui.QFrame.Raised)
        self.subscribed.setObjectName(_fromUtf8("subscribed"))
        self.tabWidget = QtGui.QTabWidget(self.subscribed)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 551, 341))
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setEnabled(True)
        self.tab.setAutoFillBackground(True)
        self.tab.setObjectName(_fromUtf8("tab"))
        self.btn_teleport = QtGui.QPushButton(self.tab)
        self.btn_teleport.setGeometry(QtCore.QRect(360, 250, 161, 31))
        self.btn_teleport.setObjectName(_fromUtf8("btn_teleport"))
        self.label_name = QtGui.QLabel(self.tab)
        self.label_name.setGeometry(QtCore.QRect(40, 20, 241, 16))
        self.label_name.setObjectName(_fromUtf8("label_name"))
        self.check_Maintenir = QtGui.QCheckBox(self.tab)
        self.check_Maintenir.setGeometry(QtCore.QRect(60, 180, 361, 21))
        self.check_Maintenir.setObjectName(_fromUtf8("check_Maintenir"))
        self.check_Entretien = QtGui.QCheckBox(self.tab)
        self.check_Entretien.setGeometry(QtCore.QRect(60, 210, 371, 26))
        self.check_Entretien.setObjectName(_fromUtf8("check_Entretien"))
        self.groupBox = QtGui.QGroupBox(self.tab)
        self.groupBox.setGeometry(QtCore.QRect(50, 50, 391, 121))
        self.groupBox.setCheckable(True)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.input_adrLivaison = QtGui.QLineEdit(self.groupBox)
        self.input_adrLivaison.setEnabled(True)
        self.input_adrLivaison.setGeometry(QtCore.QRect(20, 32, 351, 31))
        self.input_adrLivaison.setInputMask(_fromUtf8(""))
        self.input_adrLivaison.setDragEnabled(False)
        self.input_adrLivaison.setReadOnly(False)
        self.input_adrLivaison.setObjectName(_fromUtf8("input_adrLivaison"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setEnabled(True)
        self.label_9.setGeometry(QtCore.QRect(230, 80, 41, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.input_timeLivraison = QtGui.QTimeEdit(self.groupBox)
        self.input_timeLivraison.setEnabled(True)
        self.input_timeLivraison.setGeometry(QtCore.QRect(280, 80, 91, 21))
        self.input_timeLivraison.setObjectName(_fromUtf8("input_timeLivraison"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setAutoFillBackground(True)
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.btn_getCar = QtGui.QPushButton(self.tab_2)
        self.btn_getCar.setGeometry(QtCore.QRect(100, 170, 291, 51))
        self.btn_getCar.setObjectName(_fromUtf8("btn_getCar"))
        self.label_immat = QtGui.QLabel(self.tab_2)
        self.label_immat.setGeometry(QtCore.QRect(30, 80, 501, 71))
        self.label_immat.setAlignment(QtCore.Qt.AlignCenter)
        self.label_immat.setObjectName(_fromUtf8("label_immat"))
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_settings = QtGui.QWidget()
        self.tab_settings.setAutoFillBackground(True)
        self.tab_settings.setObjectName(_fromUtf8("tab_settings"))
        self.btn_desinscrire = QtGui.QPushButton(self.tab_settings)
        self.btn_desinscrire.setGeometry(QtCore.QRect(320, 160, 171, 31))
        self.btn_desinscrire.setObjectName(_fromUtf8("btn_desinscrire"))
        self.label_2 = QtGui.QLabel(self.tab_settings)
        self.label_2.setGeometry(QtCore.QRect(30, 30, 521, 31))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.tab_settings)
        self.label_3.setGeometry(QtCore.QRect(30, 130, 341, 21))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.btn_packGaranti = QtGui.QPushButton(self.tab_settings)
        self.btn_packGaranti.setGeometry(QtCore.QRect(380, 70, 111, 31))
        self.btn_packGaranti.setObjectName(_fromUtf8("btn_packGaranti"))
        self.tabWidget.addTab(self.tab_settings, _fromUtf8(""))
        self.home = QtGui.QFrame(self.centralwidget)
        self.home.setGeometry(QtCore.QRect(-1, -1, 551, 341))
        self.home.setAutoFillBackground(True)
        self.home.setFrameShape(QtGui.QFrame.StyledPanel)
        self.home.setFrameShadow(QtGui.QFrame.Raised)
        self.home.setObjectName(_fromUtf8("home"))
        self.btn_guest = QtGui.QPushButton(self.home)
        self.btn_guest.setGeometry(QtCore.QRect(290, 190, 231, 121))
        self.btn_guest.setObjectName(_fromUtf8("btn_guest"))
        self.label = QtGui.QLabel(self.home)
        self.label.setGeometry(QtCore.QRect(50, 30, 221, 71))
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.home)
        self.label_4.setGeometry(QtCore.QRect(50, 140, 221, 31))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.btn_subscriber = QtGui.QPushButton(self.home)
        self.btn_subscriber.setGeometry(QtCore.QRect(40, 190, 221, 121))
        self.btn_subscriber.setObjectName(_fromUtf8("btn_subscriber"))
        self.guest = QtGui.QFrame(self.centralwidget)
        self.guest.setEnabled(True)
        self.guest.setGeometry(QtCore.QRect(0, 0, 551, 341))
        self.guest.setAccessibleDescription(_fromUtf8(""))
        self.guest.setAutoFillBackground(True)
        self.guest.setFrameShape(QtGui.QFrame.Panel)
        self.guest.setFrameShadow(QtGui.QFrame.Raised)
        self.guest.setObjectName(_fromUtf8("guest"))
        self.tabWidget_2 = QtGui.QTabWidget(self.guest)
        self.tabWidget_2.setEnabled(True)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 551, 341))
        self.tabWidget_2.setToolTip(_fromUtf8(""))
        self.tabWidget_2.setAutoFillBackground(True)
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setAutoFillBackground(True)
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.btn_teleport_2 = QtGui.QPushButton(self.tab_3)
        self.btn_teleport_2.setGeometry(QtCore.QRect(190, 200, 161, 31))
        self.btn_teleport_2.setObjectName(_fromUtf8("btn_teleport_2"))
        self.label_name_2 = QtGui.QLabel(self.tab_3)
        self.label_name_2.setGeometry(QtCore.QRect(40, 20, 441, 131))
        self.label_name_2.setObjectName(_fromUtf8("label_name_2"))
        self.tabWidget_2.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setAutoFillBackground(True)
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.btn_getCar_2 = QtGui.QPushButton(self.tab_4)
        self.btn_getCar_2.setGeometry(QtCore.QRect(120, 150, 291, 51))
        self.btn_getCar_2.setObjectName(_fromUtf8("btn_getCar_2"))
        self.label_7 = QtGui.QLabel(self.tab_4)
        self.label_7.setGeometry(QtCore.QRect(40, 40, 351, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.input_numTicket = QtGui.QLineEdit(self.tab_4)
        self.input_numTicket.setGeometry(QtCore.QRect(40, 70, 461, 33))
        self.input_numTicket.setObjectName(_fromUtf8("input_numTicket"))
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setAutoFillBackground(True)
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.formLayoutWidget = QtGui.QWidget(self.tab_5)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 50, 491, 74))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.nomLabel = QtGui.QLabel(self.formLayoutWidget)
        self.nomLabel.setObjectName(_fromUtf8("nomLabel"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.nomLabel)
        self.input_lastName = QtGui.QLineEdit(self.formLayoutWidget)
        self.input_lastName.setObjectName(_fromUtf8("input_lastName"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.input_lastName)
        self.prenomLabel = QtGui.QLabel(self.formLayoutWidget)
        self.prenomLabel.setObjectName(_fromUtf8("prenomLabel"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.prenomLabel)
        self.input_firstName = QtGui.QLineEdit(self.formLayoutWidget)
        self.input_firstName.setObjectName(_fromUtf8("input_firstName"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.input_firstName)
        self.label_5 = QtGui.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(30, 20, 311, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_6 = QtGui.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(30, 130, 151, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.tab_5)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(180, 130, 341, 71))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.numeroDeCarteLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.numeroDeCarteLabel.setObjectName(_fromUtf8("numeroDeCarteLabel"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.numeroDeCarteLabel)
        self.numeroDeCarteLineEdit = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.numeroDeCarteLineEdit.setObjectName(_fromUtf8("numeroDeCarteLineEdit"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.numeroDeCarteLineEdit)
        self.dateDExpirationLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.dateDExpirationLabel.setObjectName(_fromUtf8("dateDExpirationLabel"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.dateDExpirationLabel)
        self.input_date = QtGui.QDateEdit(self.formLayoutWidget_2)
        self.input_date.setObjectName(_fromUtf8("input_date"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.input_date)
        self.cryptogrammeVisuelLabel = QtGui.QLabel(self.formLayoutWidget_2)
        self.cryptogrammeVisuelLabel.setObjectName(_fromUtf8("cryptogrammeVisuelLabel"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.cryptogrammeVisuelLabel)
        self.input_crypto = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.input_crypto.setObjectName(_fromUtf8("input_crypto"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.input_crypto)
        self.check_packGaranti = QtGui.QCheckBox(self.tab_5)
        self.check_packGaranti.setGeometry(QtCore.QRect(30, 240, 131, 21))
        self.check_packGaranti.setObjectName(_fromUtf8("check_packGaranti"))
        self.pushButton = QtGui.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(430, 270, 92, 27))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.label_adresseI = QtGui.QLabel(self.tab_5)
        self.label_adresseI.setGeometry(QtCore.QRect(30, 210, 151, 21))
        self.label_adresseI.setObjectName(_fromUtf8("label_adresseI"))
        self.input_adresseI = QtGui.QLineEdit(self.tab_5)
        self.input_adresseI.setGeometry(QtCore.QRect(90, 210, 431, 20))
        self.input_adresseI.setObjectName(_fromUtf8("input_adresseI"))
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.guest_recover = QtGui.QFrame(self.centralwidget)
        self.guest_recover.setGeometry(QtCore.QRect(-1, -1, 551, 341))
        self.guest_recover.setAutoFillBackground(True)
        self.guest_recover.setFrameShape(QtGui.QFrame.StyledPanel)
        self.guest_recover.setFrameShadow(QtGui.QFrame.Raised)
        self.guest_recover.setObjectName(_fromUtf8("guest_recover"))
        self.label_8 = QtGui.QLabel(self.guest_recover)
        self.label_8.setGeometry(QtCore.QRect(30, 10, 381, 121))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        consumer_home.setCentralWidget(self.centralwidget)

        self.retranslateUi(consumer_home)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(consumer_home)

    def retranslateUi(self, consumer_home):
        consumer_home.setWindowTitle(_translate("consumer_home", "DreamPark", None))
        self.btn_teleport.setText(_translate("consumer_home", "Valider", None))
        self.label_name.setText(_translate("consumer_home", "Bonjour Alexandre,", None))
        self.check_Maintenir.setText(_translate("consumer_home", "Maintenir mon véhicule (+3 euros)", None))
        self.check_Entretien.setText(_translate("consumer_home", "Entretenir mon véhicule (+4 euros)", None))
        self.groupBox.setTitle(_translate("consumer_home", "se faire livrer", None))
        self.input_adrLivaison.setText(_translate("consumer_home", "Adresse de livraison", None))
        self.label_9.setText(_translate("consumer_home", "Heure : ", None))
        self.input_timeLivraison.setDisplayFormat(_translate("consumer_home", "HH:mm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("consumer_home", "Se garer", None))
        self.btn_getCar.setText(_translate("consumer_home", "Récupérer maintenant", None))
        self.label_immat.setText(_translate("consumer_home", "Votre véhicule immaticulé 12-ABS-31  est actuellement dans notre parking.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("consumer_home", "Récupérer le véhicule", None))
        self.btn_desinscrire.setText(_translate("consumer_home", "Supprimer mon compte", None))
        self.label_2.setText(_translate("consumer_home", "Vous inscrire à un pack garanti vous permet d\'avoir une place toujours \n"
"disponible pour vous :", None))
        self.label_3.setText(_translate("consumer_home", "Si vous voulez supprimer votre compte :", None))
        self.btn_packGaranti.setText(_translate("consumer_home", "Se désinscrire", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_settings), _translate("consumer_home", "Mon compte", None))
        self.btn_guest.setText(_translate("consumer_home", "Non abonné", None))
        self.label.setText(_translate("consumer_home", "Bienvenue!", None))
        self.label_4.setText(_translate("consumer_home", "Veuillez choisir votre statut :", None))
        self.btn_subscriber.setText(_translate("consumer_home", "Abonné", None))
        self.btn_teleport_2.setText(_translate("consumer_home", "Se garer", None))
        self.label_name_2.setText(_translate("consumer_home", "Bonjour,\n"
"Nous avons détecté votre véhicule, vous pouvez vous garer. ", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_3), _translate("consumer_home", "Se garer", None))
        self.btn_getCar_2.setText(_translate("consumer_home", "Récupérer maintenant", None))
        self.label_7.setText(_translate("consumer_home", "Veuillez saisir votre numéro de ticket :", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("consumer_home", "Récupérer le véhicule", None))
        self.nomLabel.setText(_translate("consumer_home", "Nom", None))
        self.prenomLabel.setText(_translate("consumer_home", "Prenom", None))
        self.label_5.setText(_translate("consumer_home", "Pour vous abonner veuillez remplir ces champs:", None))
        self.label_6.setText(_translate("consumer_home", "Mode de paiement:", None))
        self.numeroDeCarteLabel.setText(_translate("consumer_home", "Numero de carte", None))
        self.dateDExpirationLabel.setText(_translate("consumer_home", "Date d\'expiration", None))
        self.input_date.setDisplayFormat(_translate("consumer_home", "MM/yy", None))
        self.cryptogrammeVisuelLabel.setText(_translate("consumer_home", "Cryptogramme Visuel", None))
        self.check_packGaranti.setText(_translate("consumer_home", "Pack garantie", None))
        self.pushButton.setText(_translate("consumer_home", "Je m\'abonne", None))
        self.label_adresseI.setText(_translate("consumer_home", "Adresse :", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("consumer_home", "S\'abonner", None))
        self.label_8.setText(_translate("consumer_home", "Vous avez garé votre voiture durant 10 jours:\n"
"\n"
"\n"
"Le montant à payer est de 79 euros.\n"
"Veuillez insérer les coordonnées de votre carte bancaire:", None))

